module.exports = [
    {
        id: generateUUID(),
        product_name: "Luxurious Shampoo",
        product_price: "19.99",
        quantity: 100,
        category: "Hair Care",
        product_image: "luxurious_shampoo.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: generateUUID(),
        product_name: "Organic Body Wash",
        product_price: "14.99",
        quantity: 75,
        category: "Body Care",
        product_image: "organic_body_wash.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: generateUUID(),
        product_name: "Natural Hand Soap",
        product_price: "9.99",
        quantity: 50,
        category: "Hand Care",
        product_image: "natural_hand_soap.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: generateUUID(),
        product_name: "Refreshing Face Cleanser",
        product_price: "24.99",
        quantity: 60,
        category: "Skincare",
        product_image: "refreshing_face_cleanser.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: generateUUID(),
        product_name: "Aromatherapy Bath Bombs",
        product_price: "29.99",
        quantity: 40,
        category: "Bath",
        product_image: "aromatherapy_bath_bombs.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: generateUUID(),
        product_name: "Soothing Lavender Lotion",
        product_price: "12.99",
        quantity: 80,
        category: "Body Care",
        product_image: "soothing_lavender_lotion.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: generateUUID(),
        product_name: "Exfoliating Face Scrub",
        product_price: "16.99",
        quantity: 70,
        category: "Skincare",
        product_image: "exfoliating_face_scrub.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: generateUUID(),
        product_name: "Moisturizing Lip Balm",
        product_price: "4.99",
        quantity: 120,
        category: "Lip Care",
        product_image: "moisturizing_lip_balm.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: generateUUID(),
        product_name: "Eucalyptus Shower Gel",
        product_price: "15.99",
        quantity: 55,
        category: "Body Care",
        product_image: "eucalyptus_shower_gel.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: generateUUID(),
        product_name: "Revitalizing Hair Conditioner",
        product_price: "17.99",
        quantity: 90,
        category: "Hair Care",
        product_image: "revitalizing_hair_conditioner.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
]