module.exports = [
  {
    id: '9e96ba90-b5d8-44f9-96e4-31b4570b6503',
    user_name: "John Doe",
    user_email: "john.doe@example.com",
    user_pronouns: "he/him",
    contact_phone: "555-123-4567",
    name_pronunciation: "d͡ʒɑn doʊ",
    user_icon: "john_doe.png",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: '747afa2c-f054-46a4-bd14-ae0a74a09da9',
    user_name: "Alice Smith",
    user_email: "alice.smith@example.com",
    user_pronouns: "she/her",
    contact_phone: "555-987-6543",
    name_pronunciation: "ˈælɪs smɪθ",
    user_icon: "alice_smith.png",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 'a62e9086-0ece-427b-b2a9-2788c3c07662',
    user_name: "Bob Johnson",
    user_email: "bob.johnson@example.com",
    user_pronouns: "they/them",
    contact_phone: "555-567-8901",
    name_pronunciation: "bɑb ˈdʒɑnsən",
    user_icon: "bob_johnson.png",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 'a1c02248-7512-4b85-9b97-cf5225918fbc',
    user_name: "Emily Brown",
    user_email: "emily.brown@example.com",
    user_pronouns: "she/her",
    contact_phone: "555-234-5678",
    name_pronunciation: "ˈɛməli braʊn",
    user_icon: "emily_brown.png",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: '27e7d6f5-24fb-4f3d-a43d-f8505cc7970d',
    user_name: "Michael Wilson",
    user_email: "michael.wilson@example.com",
    user_pronouns: "he/him",
    contact_phone: "555-876-5432",
    name_pronunciation: "ˈmaɪkəl ˈwɪlsən",
    user_icon: "michael_wilson.png",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: '9a76f912-938c-4393-9b90-d001e7d4066a',
    user_name: "Linda Davis",
    user_email: "linda.davis@example.com",
    user_pronouns: "she/her",
    contact_phone: "555-345-6789",
    name_pronunciation: "ˈlɪndə ˈdeɪvɪs",
    user_icon: "linda_davis.png",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: '2fddbff6-8115-4b38-80d0-4dd36644f700',
    user_name: "David Lee",
    user_email: "david.lee@example.com",
    user_pronouns: "he/him",
    contact_phone: "555-765-4321",
    name_pronunciation: "ˈdeɪvɪd li",
    user_icon: "david_lee.png",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 'ccb1a00d-7940-40d3-9887-e7ad647c65d6',
    user_name: "Sarah Miller",
    user_email: "sarah.miller@example.com",
    user_pronouns: "she/her",
    contact_phone: "555-456-7890",
    name_pronunciation: "ˈsɛrə ˈmɪlər",
    user_icon: "sarah_miller.png",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: '4892d513-8c11-4bf6-a66e-852e92b80ad1',
    user_name: "James Clark",
    user_email: "james.clark@example.com",
    user_pronouns: "he/him",
    contact_phone: "555-654-3210",
    name_pronunciation: "ˈdʒeɪmz klɑrk",
    user_icon: "james_clark.png",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 'bc62c34e-5b78-4366-a354-4fb9d338b6f8',
    user_name: "Olivia White",
    user_email: "olivia.white@example.com",
    user_pronouns: "she/her",
    contact_phone: "555-234-5678",
    name_pronunciation: "oˈlɪviə waɪt",
    user_icon: "olivia_white.png",
    created_at: new Date(),
    updated_at: new Date(),
  },
]